version: "3.7"  # docker compose format version

services:
# every time we run a docker-compose, it automatically creates a network and link the services for us

# docker run -dp 3000:3000 --name multi_container_app --network net_todo_app -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=secret -e MYSQL_DB=todos simple_app:v2

  app:
    image: pablokbs/getting-started:v2
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  
# docker run --name my_container_3 -d --network net_todo_app --network-alias mysql -v todo_mysql_data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=todos mysql:5.7

  mysql:  # networl-alias (host)
    image: mysql:5.7
    volumes:
      - ./todo_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos


# docker exec -it 36469f0d15aa mysql -p
# docker-compose down